# Generated by Django 3.2.8 on 2021-10-25 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='date_end',
            field=models.DateField(blank=True, help_text='Оставить поле пустым, если сейчас работаете', null=True, verbose_name='Конец работы'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Начало работы'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='whom',
            field=models.CharField(default=django.utils.timezone.now, help_text='Например: Разработчик, Архитектор, Программист, ....', max_length=255, verbose_name='Кем работаете'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workplace',
            name='text',
            field=models.CharField(help_text='Название компании. Например: Rocket Science', max_length=255, verbose_name='Место работы'),
        ),
    ]
