# Generated by Django 3.2.9 on 2022-01-17 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_career_meeting',
            field=models.DateField(default=datetime.date.today, verbose_name='Последняя карьерная встреча'),
        ),
    ]
