version: '3.3'

services:
  backend:
    container_name: pr_backend
    restart: always
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static/
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - TIME_ZONE=Europe/Moscow
    depends_on:
      - postgres

  postgres:
    container_name: pr_postgres
    image: postgres:13.3
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_HOST: '${POSTGRES_HOST}'
      POSTGRES_POST: '${POSTGRES_POST}'
      CONFIGS: "listen_addresses:'*',max_replication_slots:5"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
      - ./data/shared/backups:/backups
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  static_volume: