version: '3.3'

services:
  nginx:
    container_name: pr_nginx
    build: ./nginx
    volumes:
      - ./portfolio_generate/static:/home/app/portfolio/portfolio_generate/static
    ports:
      - 8010:80
    depends_on:
      - backend

  backend:
    container_name: pr_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "python manage.py migrate &&  gunicorn portfolio_generate.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/home/app/portfolio
      - ./portfolio_generate/static:/home/app/portfolio/portfolio_generate/static
    expose:
      - 8000
    env_file:
      - .env.prod
    environment:
      - POSTGRES_HOST=postgres
      - TIME_ZONE=Europe/Moscow
    depends_on:
      - postgres

  postgres:
    container_name: pr_postgres
    image: postgres:13.3
    restart: always
    hostname: postgres
#    user: "3203:3203"
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_HOST: '${POSTGRES_HOST}'
      POSTGRES_POST: '${POSTGRES_POST}'
      CONFIGS: "listen_addresses:'*',max_replication_slots:5"
    expose:
      - 5432
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  static_volume: