version: '3.3'

services:
  web:
    container_name: pr_web
    restart: always
    build:
      context: ./
      dockerfile: _docker/web/Dockerfile
    command:
      - bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/home/app/portfolio
      - ./src/portfolio_generate/static/:/home/app/portfolio/portfolio_generate/static
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - TIME_ZONE=Europe/Moscow
    depends_on:
      - db

  db:
    container_name: pr_db
    image: postgres:13.3
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_HOST: '${POSTGRES_HOST}'
      POSTGRES_PORT: '${POSTGRES_PORT}'
      CONFIGS: "listen_addresses:'*',max_replication_slots:5"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 5