# Generated by Django 3.2.9 on 2022-01-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_last_career_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_career_meeting',
            field=models.DateField(blank=True, null=True, verbose_name='Последняя карьерная встреча'),
        ),
    ]
