# Generated by Django 3.2.9 on 2022-01-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_portfolio_experience_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='completed',
            field=models.DateField(blank=True, help_text='Оставить пустым - если работа идет над проектом', null=True, verbose_name='Завершил работу над проектом'),
        ),
        migrations.AddField(
            model_name='experience',
            name='started',
            field=models.DateField(blank=True, null=True, verbose_name='Приступил к проекту'),
        ),
    ]
