# Generated by Django 3.2.8 on 2021-10-22 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Выводить')),
            ],
            options={
                'verbose_name': 'Опыт',
                'verbose_name_plural': 'Опыт',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_with', models.DateTimeField(help_text='Указать год, с которого начали работать', verbose_name='Опыт работы с')),
                ('stack', models.IntegerField(choices=[(0, 'Fullstack'), (1, 'Back-End'), (2, 'Front-End')], verbose_name='Стэк')),
                ('setting', models.JSONField(default={'portfolio': False, 'work_places': False}, verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, 'Язык программирования'), (1, 'Фреймворк'), (2, 'Библиотека'), (3, 'DBMS'), (4, 'Cloud - сервис'), (5, 'Другое'), (6, 'Инструменты разработки'), (7, 'App type')], verbose_name='Категория')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Технологии',
                'verbose_name_plural': 'Технологии',
                'ordering': ['category', 'text'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(help_text='Например: Junior, Middle, Senio, DevOps, Архитектор, ...', max_length=255, verbose_name='Градация')),
                ('salary', models.IntegerField(blank=True, default=0, null=True, verbose_name='Желаемая зарплата')),
                ('post', models.CharField(blank=True, max_length=255, null=True, verbose_name='Желаемая должность')),
                ('travel_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время в пути')),
                ('employment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Занятость')),
                ('schedule', models.IntegerField(blank=True, choices=[(0, 'Удаленный'), (1, 'Полный'), (2, 'Гибкий')], null=True, verbose_name='График работы')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', verbose_name='Порфолио')),
            ],
            options={
                'verbose_name': 'Пожелания для устройства',
                'verbose_name_plural': 'Пожелания для устройства',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на проект')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('tech', models.ManyToManyField(to='portfolio.Tech', verbose_name='Технологии проекта')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tech',
            field=models.ManyToManyField(to='portfolio.Tech', verbose_name='Используемые технологии'),
        ),
    ]
