# Generated by Django 3.2.9 on 2022-01-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20220121_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='experience_with',
            field=models.DateField(help_text='Указать год, с которого начали работать', verbose_name='Опыт работы с'),
        ),
    ]
